FROM python:3.9

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100

RUN pip install poetry

WORKDIR /src
COPY . /src/

# Project initialization:
RUN POETRY_VIRTUALENVS_CREATE=false poetry install
RUN poetry install --no-dev --no-interaction --no-ansi

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "80"]
